# Generated by Django 2.0.8 on 2018-09-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0056_message_metadata'),
        ('msgs', '0060_auto_20180814_2109'),
    ]

    operations = [
    ]
